//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEmploi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emploi
    {
        public decimal idEmploi { get; set; }
        public Nullable<System.DateTime> dateEntree { get; set; }
        public Nullable<System.DateTime> dateSortie { get; set; }
        public Nullable<decimal> numDossier { get; set; }
        public Nullable<decimal> numeroEntreprise { get; set; }
        public string codeProfession { get; set; }
    
        public virtual Travailleur Travailleur { get; set; }
    }
}
